vectorface_backlog_main:
    pattern:  /
    defaults: { _controller: VectorfaceBacklogBundle:Default:index }

vectorface_backlog_autocomplete:
    pattern:  /autocomplete
    defaults: { _controller: VectorfaceBacklogBundle:Default:autocomplete }

vectorface_backlog_add:
    pattern:  /add/{ixBug}
    defaults: { _controller: VectorfaceBacklogBundle:Default:add }

vectorface_backlog_delete:
    pattern:  /delete/{ixBug}
    defaults: { _controller: VectorfaceBacklogBundle:Default:delete }